### ISSUE TITLE
segfault when viewing message with mime pgp signature

### ISSUE THREAD

**Issue by ian-kelling** [djcb/mu#1050]
```
;; mu> cmd:view docid:7854
gpg-agent[16344]: gpg-agent running and available

Program received signal SIGSEGV, Segmentation fault.
__strncmp_sse42 () at ../sysdeps/x86_64/multiarch/strcmp-sse42.S:164
164	../sysdeps/x86_64/multiarch/strcmp-sse42.S: No such file or directory.
(gdb) bt
#0  __strncmp_sse42 () at ../sysdeps/x86_64/multiarch/strcmp-sse42.S:164
#1  0x00007ffff7775a04 in _g_mime_get_gpg_version () from /usr/lib/x86_64-linux-gnu/libgmime-2.6.so.0
#2  0x00007ffff7775b30 in g_mime_gpg_context_new () from /usr/lib/x86_64-linux-gnu/libgmime-2.6.so.0
#3  0x000055555558c199 in get_gpg_crypto_context ()
#4  0x000055555558c25a in get_crypto_context ()
#5  0x000055555558c95d in mu_msg_crypto_verify_part ()
#6  0x0000555555576064 in check_signature ()
#7  0x00005555555769d8 in handle_mime_object ()
#8  0x0000555555576c44 in mu_msg_part_foreach ()
#9  0x000055555557876d in append_sexp_parts ()
#10 0x00005555555789fc in append_message_file_parts ()
#11 0x0000555555578ef9 in mu_msg_to_sexp ()
#12 0x0000555555568d12 in cmd_view ()
#13 0x0000555555568e1b in handle_args ()
#14 0x0000555555568fb9 in mu_cmd_server ()
#15 0x000055555556aa5e in with_store ()
#16 0x000055555556ad6c in mu_cmd_execute ()
#17 0x000055555556135e in main ()
```

I'm guessing that gmime has a bug causing it to crash and we could also be sending it bad input.

So I checked some info for that:

On debian stretch, 
Package: libgmime-2.6-0                  
Version: 2.6.22-2

There's no debbugs for this package, one unrelated for the source package
https://bugs.debian.org/cgi-bin/pkgreport.cgi?dist=unstable;package=libgmime-2.6-0
no open bugs in the upstream bug tracker, using product: gmime, no closed bugs searching for the deepest gmime function in the trace.
https://bugzilla.gnome.org/query.cgi?format=advanced

Reprod with mu 0.9.18-1 from debian and from git, version ff94595fad270

**Comment by ian-kelling** [comment]
So, figured it out. I accidentally put a bash script called gpg in a directory in $PATH. So, probably a bug in gmime, but also user error.
