### ISSUE TITLE
mu signal 11 segv on find

### ISSUE THREAD

**Issue by ian-kelling** [djcb/mu#1922]
## Actual behavior

2021-02-04 19:22:53.324 -> (find :query "maildir:\"/Sent\"" :threads t :sortfield :date :descending t :maxnum 1000 :skip-dups t :include-related t)

error in process sentinel: mu4e~proc-sentinel: mu server process received signal 11
error in process sentinel: mu server process received signal 11

```
#0  0x00005574b43ace58 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::c_str() const (this=<optimized out>) at /usr/include/c++/7/bits/basic_string.h:2281
#1  0x00005574b43ace58 in <lambda(const Container*, const Container*)>::operator() (__closure=<optimized out>, c2=<optimized out>, c1=<optimized out>) at mu-query-threads.cc:452
#2  0x00005574b43ace58 in std::_Rb_tree<Container*, Container*, std::_Identity<Container*>, sort_siblings(Container::children_type&, const ThreadPathVec&, size_t, bool, const string&)::<lambda(const Container*, const Container*)>, std::allocator<Container*> >::_M_get_insert_unique_pos (__k=@0x5574b6f35010: 0x5574b7ef9be8, this=0x7ffdfd671670)
    at /usr/include/c++/7/bits/stl_tree.h:2038
#3  0x00005574b43ace58 in std::_Rb_tree<Container*, Container*, std::_Identity<Container*>, sort_siblings(Container::children_type&, const ThreadPathVec&, size_t, bool, const string&)::<lambda(const Container*, const Container*)>, std::allocator<Container*> >::_M_emplace_unique<Container* const> (this=0x7ffdfd671670) at /usr/include/c++/7/bits/stl_tree.h:2356
#4  0x00005574b43ace58 in std::set<Container*, sort_siblings(Container::children_type&, const ThreadPathVec&, size_t, bool, const string&)::<lambda(const Container*, const Container*)>, std::allocator<Container*> >::emplace<Container* const> (this=0x7ffdfd671670) at /usr/include/c++/7/bits/stl_set.h:453
#5  0x00005574b43ace58 in sort_siblings(Container::children_type&, Mu::ThreadPathVec const&, size_t, bool, std::__cxx11::string const&) (siblings=..., parent_path_vec=std::vector of length 6, capacity 10 = {...}, segment_size=segment_size@entry=4, descending=descending@entry=true, last_subject="Re: Newzbin Password") at mu-query-threads.cc:459
#6  0x00005574b43ad215 in sort_siblings(Container::children_type&, Mu::ThreadPathVec const&, size_t, bool, std::__cxx11::string const&) (siblings=..., parent_path_vec=std::vector of length 5, capacity 8 = {...}, segment_size=segment_size@entry=4, descending=descending@entry=true, last_subject="Re: FW: Newzbin Password") at mu-query-threads.cc:479
#7  0x00005574b43ad215 in sort_siblings(Container::children_type&, Mu::ThreadPathVec const&, size_t, bool, std::__cxx11::string const&) (siblings=..., parent_path_vec=std::vector of length 4, capacity 6 = {...}, segment_size=segment_size@entry=4, descending=descending@entry=true, last_subject="Re: Vegas Trip") at mu-query-threads.cc:479
#8  0x00005574b43ad215 in sort_siblings(Container::children_type&, Mu::ThreadPathVec const&, size_t, bool, std::__cxx11::string const&) (siblings=..., parent_path_vec=std::vector of length 3, capacity 4 = {...}, segment_size=segment_size@entry=4, descending=descending@entry=true, last_subject="Re: Vegas Trip") at mu-query-threads.cc:479
#9  0x00005574b43ad215 in sort_siblings(Container::children_type&, Mu::ThreadPathVec const&, size_t, bool, std::__cxx11::string const&) (siblings=..., parent_path_vec=std::vector of length 2, capacity 2 = {...}, segment_size=segment_size@entry=4, descending=descending@entry=true, last_subject="Re: Yo man, Favor") at mu-query-threads.cc:479
#10 0x00005574b43ad215 in sort_siblings(Container::children_type&, Mu::ThreadPathVec const&, size_t, bool, std::__cxx11::string const&) (siblings=..., parent_path_vec=std::vector of length 1, capacity 1 = {...}, segment_size=segment_size@entry=4, descending=descending@entry=true, last_subject="") at mu-query-threads.cc:479
#11 0x00005574b43b0007 in sort_siblings (descending=true, id_table=std::unordered_map with 14238 elements = {...}) at mu-query-threads.cc:506
#12 0x00005574b43b0007 in calculate_threads_real<Mu::QueryResults> (descending=true, sort_field=<optimized out>, qres=...) at mu-query-threads.cc:551
#13 0x00005574b43b0007 in Mu::calculate_threads(Mu::QueryResults&, unsigned char, bool) (qres=..., sort_field=sort_field@entry=16 '\020', descending=descending@entry=true) at mu-query-threads.cc:561
#14 0x00005574b43a67b7 in Mu::Query::Private::run_threaded(Mu::QueryResults&, Xapian::Enquire&, unsigned char, Mu::QueryFlags, unsigned long) const (this=this@entry=0x5574b580f6c0, qres=..., enq=..., sortfieldid=sortfieldid@entry=16 '\020', qflags=qflags@entry=(Mu::QueryFlags::Descending | Mu::QueryFlags::SkipDuplicates | Mu::QueryFlags::IncludeRelated | Mu::QueryFlags::Threading), maxnum=1000) at mu-query.cc:144
#15 0x00005574b43a6e12 in Mu::Query::Private::run_related(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned char, Mu::QueryFlags, unsigned long) const (this=0x5574b580f6c0, expr=..., sortfieldid=<optimized out>, qflags=(Mu::QueryFlags::Descending | Mu::QueryFlags::SkipDuplicates | Mu::QueryFlags::IncludeRelated | Mu::QueryFlags::Threading), maxnum=1000) at mu-query.cc:200
#16 0x00005574b43a7255 in Mu::Query::Private::run(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned char, Mu::QueryFlags, unsigned long) const (this=<optimized out>, expr="maildir:\"/Sent\"", sortfieldid=sortfieldid@entry=16 '\020', qflags=qflags@entry=(Mu::QueryFlags::Descending | Mu::QueryFlags::SkipDuplicates | Mu::QueryFlags::IncludeRelated | Mu::QueryFlags::Threading), maxnum=maxnum@entry=1000) at mu-query.cc:210
#17 0x00005574b43a73ca in Mu::Query::run(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned char, Mu::QueryFlags, unsigned long) const (this=this@entry=0x5574b57fcb80, expr="maildir:\"/Sent\"", sortfieldid=<optimized out>, qflags=(Mu::QueryFlags::Descending | Mu::QueryFlags::SkipDuplicates | Mu::QueryFlags::IncludeRelated | Mu::QueryFlags::Threading), maxnum=maxnum@entry=1000) at mu-query.cc:230
#18 0x00005574b43b8af4 in Mu::Server::Private::find_handler(std::vector<Mu::Sexp, std::allocator<Mu::Sexp> > const&) (this=0x5574b57fcb20, params=...) at mu-server.cc:780
#19 0x00005574b43eb7e1 in std::function<void (std::vector<Mu::Sexp, std::allocator<Mu::Sexp> > const&)>::operator()(std::vector<Mu::Sexp, std::allocator<Mu::Sexp> > const&) const (__args#0=..., this=0x5574b5811f20) at /usr/include/c++/7/bits/std_function.h:706
#20 0x00005574b43eb7e1 in Mu::Command::invoke(std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, Mu::Command::CommandInfo, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Mu::Command::CommandInfo> > > const&, Mu::Sexp const&) (cmap=std::unordered_map with 14 elements = {...}, call=...) at mu-command-parser.cc:94
#21 0x00005574b43b4c6a in Mu::Server::Private::invoke(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (this=0x5574b57fcb20, expr="(find :query \"maildir:\\\"/Sent\\\"\" :threads t :sortfield :date :descending t :maxnum 1000 :skip-dups t :include-related t)") at mu-server.cc:355
#22 0x00005574b43b4d98 in Mu::Server::invoke(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (this=this@entry=0x7ffdfd672848, expr="(find :query \"maildir:\\\"/Sent\\\"\" :threads t :sortfield :date :descending t :maxnum 1000 :skip-dups t :include-related t)") at mu-server.cc:1200
#23 0x00005574b438bba3 in Mu::mu_cmd_server(Mu::_MuConfig const*, _GError**) (opts=<optimized out>, err=err@entry=0x7ffdfd672b38) at mu-cmd-server.cc:125
#24 0x00005574b438e046 in Mu::mu_cmd_execute(Mu::_MuConfig const*, _GError**) (opts=0x5574b4614da0 <MU_CONFIG>, err=0x7ffdfd672b38) at mu-cmd.cc:736
#25 0x00005574b438447c in main(int, char**) (argc=<optimized out>, argv=<optimized out>) at mu.cc:130
```

This only happens on some of my folders.

Emacs version git a92167674f6f2 from Thu Feb 4 20:52:20 2021 +0100

mu/mu4e version  58e4046cbd53 from Sat Jan 30 13:10:46 2021 +0200

This started after I upgraded from a mu dev version from august, it looks like the failing code in the trace is new, so I'll be rolling back to before it exists and will add a comment to say if that fixed it.

The failing call outside of mu code is /usr/include/c++/7/bits/stl_set.h which is libstdc++-7-dev package, version 7.5.0-3ubuntu1~18.04

My OS is trisquel 9 (most packages are same version as ubuntu 18.04).

**Comment by ian-kelling** [comment]
I found a commit where the error is gone 86e1515c71ca628456e3f1957f69c60433f1bd6c from Jan 18 2021
