### ISSUE TITLE
[mu bug] double free or corruption (!prev) crash on HEAD

### ISSUE THREAD

**Issue by stsquad** [djcb/mu#2272]
**Describe the bug**

While re-indexing due to the latest update I ran into a heap corruption bug which caused the indexer to crash..

**To Reproduce**

mu init
mu index

**Environment**

Linux, running 1a84a57e0553abd47c79924b6687543cc0584add

```
Core was generated by `mu index'.                                                                                                           
Program terminated with signal SIGABRT, Aborted.                                                                                            
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50                                                                   
50      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory. 
[Current thread is 1 (Thread 0x7fb8214ae700 (LWP 1668831))]                                                                                 
(gdb) bt                                                                                                                                    
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007fb821b3f537 in __GI_abort () at abort.c:79                                                                                       
#2  0x00007fb821b98768 in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7fb821ca6e2d "%s\n") at ../sysdeps/posix/libc_fatal.
c:155                                                                                                                                       
#3  0x00007fb821b9fa5a in malloc_printerr (str=str@entry=0x7fb821ca9230 "double free or corruption (!prev)") at malloc.c:5347
#4  0x00007fb821ba109c in _int_free (av=0x7fb81c000020, p=0x7fb6b3539c10, have_lock=<optimized out>) at malloc.c:4317
#5  0x00007fb82258d860 in g_utf8_normalize (str=str@entry=0x7fb6b35385c0 "Thank you in advance Alex.\nyou said: \"Using the QEMU's gdbstub t
o debug a guest is different from debugging QEMU by running it under gdb.\"\nif i want to see the hardware's internal which is emulated by".
.., len=len@entry=-1, mode=mode@entry=G_NORMALIZE_ALL) at ../../../glib/gunidecomp.c:552
#6  0x0000555753d3c9f1 in (anonymous namespace)::gx_utf8_flatten (len=-1, str=0x7fb6b35385c0 "Thank you in advance Alex.\nyou said: \"Using 
the QEMU's gdbstub to debug a guest is different from debugging QEMU by running it under gdb.\"\nif i want to see the hardware's internal wh
ich is emulated by"...) at ../lib/utils/mu-utils.cc:96
#7  Mu::utf8_flatten[abi:cxx11](char const*) (str=0x7fb6b35385c0 "Thank you in advance Alex.\nyou said: \"Using the QEMU's gdbstub to debug 
a guest is different from debugging QEMU by running it under gdb.\"\nif i want to see the hardware's internal which is emulated by"...) at .
./lib/utils/mu-utils.cc:134
#8  0x0000555753d4c171 in Mu::utf8_flatten(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (s="Thank
 you in advance Alex.\nyou said: \"Using the QEMU's gdbstub to debug a guest is different from debugging QEMU by running it under gdb.\"\nif
 i want to see the hardware's internal which is emulated by"...) at /usr/include/c++/10/bits/basic_string.h:186
#9  add_search_term(Xapian::Document&, Mu::Field const&, std::string const&) (doc=..., field=..., val="Thank you in advance Alex.\nyou said:
 \"Using the QEMU's gdbstub to debug a guest is different from debugging QEMU by running it under gdb.\"\nif i want to see the hardware's in
ternal which is emulated by"...) at ../lib/message/mu-document.cc:49
#10 0x0000555753d4e37e in Mu::Document::add(Mu::Field::Id, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > c
onst&) (this=this@entry=0x7fb6b351c138, id=id@entry=Mu::Field::Id::BodyText, val="Thank you in advance Alex.\nyou said: \"Using the QEMU's g
dbstub to debug a guest is different from debugging QEMU by running it under gdb.\"\nif i want to see the hardware's internal which is emula
ted by"...) at ../lib/message/mu-document.cc:70
#11 0x0000555753d44a08 in Mu::Document::add<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >(Mu::Field::Id,
 tl::optional<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > const&) (val=..., id=Mu::Field::Id::BodyText
, this=0x7fb6b351c138) at ../lib/message/mu-document.hh:168
#12 operator()<const Mu::Field&> (field=..., __closure=<optimized out>) at ../lib/message/mu-message.cc:663
#13 Mu::field_for_each<fill_document(Mu::Message::Private&)::<lambda(auto:14&&)> > (func=<optimized out>) at ../lib/message/mu-fields.hh:484
#14 fill_document(Mu::Message::Private&) (priv=...) at ../lib/message/mu-message.cc:654
#15 0x0000555753d45879 in Mu::Message::Message(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, Mu::M
essage::Options) (this=0x7fb8214adc08, path="/home/alex/Maildir/[Gmail]/Important/cur/1614858293.12743_11988.zen,U=40621:2,RS", opts=(unknow
n: 0x214adaf0)) at /usr/include/c++/10/bits/unique_ptr.h:173
#16 0x0000555753d58b64 in Mu::Message::make_from_path(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&
, Mu::Message::Options) (opts=Mu::Message::Options::None, path="/home/alex/Maildir/[Gmail]/Important/cur/1614858293.12743_11988.zen,U=40621:
2,RS") at ../lib/message/mu-message.hh:79
#17 Mu::Indexer::Private::add_message(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (this=0x555754
438c40, path="/home/alex/Maildir/[Gmail]/Important/cur/1614858293.12743_11988.zen,U=40621:2,RS") at ../lib/index/mu-indexer.cc:231
#18 0x0000555753d59650 in Mu::Indexer::Private::item_worker() (this=0x555754438c40) at ../lib/index/mu-indexer.cc:260
#19 0x00007fb821f2fed0 in  () at /lib/x86_64-linux-gnu/libstdc++.so.6
#20 0x00007fb821ce7ea7 in start_thread (arg=<optimized out>) at pthread_create.c:477
#21 0x00007fb821c17def in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

with 

```
(gdb) info threads
  Id   Target Id                           Frame 
* 1    Thread 0x7fb8214ae700 (LWP 1668831) __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
  2    Thread 0x7fb82183a880 (LWP 1668830) 0x00007fb821bdfc61 in __GI___clock_nanosleep (clock_id=clock_id@entry=0, flags=flags@entry=0, req=req@entry=0x7ffc26c3ab60, rem=rem@entry=0x7ffc26c3ab60) at ../sysdeps/unix/sysv/linux/clock_nanosleep.c:48
  3    Thread 0x7fb81b7fe700 (LWP 1668834) 0x00007fb8225335fa in sha256_transform (buf=buf@entry=0x7fb808012190, data=data@entry=0x7fb81b7fc970 "int rn, unsigned int rd)\n+{\n+    TCGv_i64 tcg_rd, tcg_rn, tcg_tmp;\n+    tcg_rd = cpu_reg(s, rd);\n+    tcg_rn = cpu_reg(s, rn);\n+\n+    tcg_tmp = tcg_temp_new_i64();\n+    tcg_gen_andi_i64(tcg_tmp, tcg_r"...) at ../../../glib/gchecksum.c:949
  4    Thread 0x7fb81bfff700 (LWP 1668833) 0x00007fb82212d082 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_construct<char*> (this=this@entry=0x7fb81bffe630, __beg=0x7fb81bffe860 "Barm", __end=0x7fb81bffe864 "") at /usr/include/c++/10/bits/basic_string.tcc:206
  5    Thread 0x7fb820cad700 (LWP 1668832) 0x00007fb821bdfc61 in __GI___clock_nanosleep (clock_id=clock_id@entry=0, flags=flags@entry=0, req=req@entry=0x7fb820cacd50, rem=rem@entry=0x7fb820cacd50) at ../sysdeps/unix/sysv/linux/clock_nanosleep.c:48
  6    Thread 0x7fb81affd700 (LWP 1668835) __lll_lock_wait (futex=futex@entry=0x5557544394d0, private=0) at lowlevellock.c:52
(gdb) 
```

**Comment by djcb** [comment]
Oh, that's not good.... is it reproducible? And if so, always with this message?

**Comment by stsquad** [comment]
Looks like it. I tried reverting the lock reduction patch on a hunch but it still failed at the same place. I'll see if I can dig out more.

**Comment by djcb** [comment]
Oh thanks for checking! It _seems_ like something inside glib, though perhaps the heap got corrupted from somewhere else...

If it's specific to this message, are you able to share it? Perhaps with any identifying information removed? Might make a good unit-test...

**Comment by stsquad** [comment]
I'm going to mark this as invalid for now. A complete clean rebuild made the problem go away. I shall keep an eye out for it crashing again but for now I'll blame a broken build.
