### ISSUE TITLE
Spam message → unresponsive Emacs

### ISSUE THREAD

**Issue by Chris00** [djcb/mu#880]
With the attached [spam message](https://github.com/djcb/mu/files/358251/spam.txt), when going on the next message, not only the headers view is "corrupted":

![Corrupted headers view](https://cloud.githubusercontent.com/assets/1255665/16749745/e7db6aa8-47cc-11e6-802f-c0dc45400072.png)

but, more importantly trying to "delete" it (`d`: moving to trash) after viewing it make Emacs irresponsive (using 100% of one CPU).  Declaring it as spam (which automatically `delete`s the message) works fine.

**Comment by djcb** [comment]
Oh, that's a pretty bad issue! I was able to reproduce it. It seems like a an emacs issue, though... perhaps you can file a bug there?

This is the backtrace I get when stopping the out-of-control emacs:
```
#0  assq_no_quit (key=key@entry=16848, list=51100227) at fns.c:1452
#1  0x00000000004b24ac in lface_from_face_name_no_resolve (f=f@entry=0x1237f90, face_name=face_name@entry=16848, signal_p=signal_p@entry=false) at xfaces.c:1862
#2  0x00000000004b250c in get_lface_attributes_no_remap (f=f@entry=0x1237f90, face_name=face_name@entry=16848, attrs=attrs@entry=0x7fffffff05f0, signal_p=signal_p@entry=false) at xfaces.c:1904
#3  0x00000000004b5b4e in get_lface_attributes (f=f@entry=0x1237f90, face_name=face_name@entry=16848, attrs=attrs@entry=0x7fffffff05f0, signal_p=signal_p@entry=false, named_merge_points=named_merge_points@entry=0x7fffffff05d0) at xfaces.c:1951
#4  0x00000000004b5c4f in merge_named_face (f=f@entry=0x1237f90, face_name=face_name@entry=16848, to=to@entry=0x7fffffff0a10, named_merge_points=0x7fffffff05d0) at xfaces.c:2172
#5  0x00000000004b527f in merge_face_ref (f=0x1237f90, face_ref=16848, to=0x7fffffff0a10, err_msgs=<optimized out>, named_merge_points=<optimized out>) at xfaces.c:2439
#6  0x00000000004b59c2 in merge_face_vectors (f=f@entry=0x1237f90, from=from@entry=0x7fffffff0770, to=to@entry=0x7fffffff0a10, named_merge_points=named_merge_points@entry=0x7fffffff0750) at xfaces.c:2099
#7  0x00000000004b5c81 in merge_named_face (f=f@entry=0x1237f90, face_name=face_name@entry=18195424, to=to@entry=0x7fffffff0a10, named_merge_points=0x7fffffff0750) at xfaces.c:2176
#8  0x00000000004b527f in merge_face_ref (f=0x1237f90, face_ref=18195424, to=0x7fffffff0a10, err_msgs=<optimized out>, named_merge_points=<optimized out>) at xfaces.c:2439
#9  0x00000000004ba1bb in face_at_buffer_position (w=0x1238fa0, pos=<optimized out>, endptr=endptr@entry=0x7fffffff0af8, limit=<optimized out>, mouse=mouse@entry=false, base_face_id=<optimized out>) at xfaces.c:5958
#10 0x0000000000440bc3 in handle_face_prop (it=0x7fffffff7eb0) at xdisp.c:3863
#11 0x000000000043e23a in handle_stop (it=it@entry=0x7fffffff7eb0) at xdisp.c:3371
#12 0x0000000000442af2 in next_element_from_buffer (it=0x7fffffff7eb0) at xdisp.c:8321
#13 0x0000000000440f55 in get_next_display_element (it=it@entry=0x7fffffff7eb0) at xdisp.c:6921
#14 0x00000000004430c1 in move_it_in_display_line_to (it=it@entry=0x7fffffff7eb0, to_charpos=<optimized out>, to_x=3710, op=op@entry=(MOVE_TO_X | MOVE_TO_POS)) at xdisp.c:8662
#15 0x000000000044d519 in display_line (it=it@entry=0x7fffffff7eb0) at xdisp.c:20465
#16 0x000000000044ed1a in try_window (window=window@entry=19107749, pos=..., flags=flags@entry=1) at xdisp.c:17198
#17 0x00000000004629aa in redisplay_window (window=19107749, just_this_one_p=just_this_one_p@entry=true) at xdisp.c:16654
#18 0x0000000000465c4e in redisplay_window_1 (window=window@entry=19107749) at xdisp.c:14454
#19 0x000000000055945e in internal_condition_case_1 (bfun=bfun@entry=0x465c20 <redisplay_window_1>, arg=19107749, handlers=<optimized out>, hfun=hfun@entry=0x42ba20 <redisplay_window_error>) at eval.c:1333
#20 0x000000000045316c in redisplay_internal () at xdisp.c:14079
#21 0x00000000004544c5 in redisplay () at xdisp.c:13214
#22 0x00000000004f332b in read_char (commandflag=commandflag@entry=1, map=map@entry=68809891, prev_event=0, used_mouse_menu=used_mouse_menu@entry=0x7fffffffd22b, end_time=end_time@entry=0x0) at keyboard.c:2477
#23 0x00000000004f5cf0 in read_key_sequence (keybuf=keybuf@entry=0x7fffffffd300, prompt=prompt@entry=0, dont_downcase_last=dont_downcase_last@entry=false, can_return_switch_frame=can_return_switch_frame@entry=true, fix_current_buffer=fix_current_buffer@entry=true, prevent_redisplay=prevent_redisplay@entry=false, bufsize=30)
    at keyboard.c:9063
#24 0x00000000004f7816 in command_loop_1 () at keyboard.c:1365
#25 0x00000000005593d2 in internal_condition_case (bfun=bfun@entry=0x4f7620 <command_loop_1>, handlers=handlers@entry=19152, hfun=hfun@entry=0x4ee390 <cmd_error>) at eval.c:1309
#26 0x00000000004e9abc in command_loop_2 (ignore=ignore@entry=0) at keyboard.c:1107
#27 0x0000000000559373 in internal_catch (tag=tag@entry=45984, func=func@entry=0x4e9aa0 <command_loop_2>, arg=arg@entry=0) at eval.c:1074
#28 0x00000000004e9a79 in command_loop () at keyboard.c:1086
#29 0x00000000004edf97 in recursive_edit_1 () at keyboard.c:692
#30 0x00000000004ee2d8 in Frecursive_edit () at keyboard.c:763
#31 0x0000000000418abb in main (argc=2, argv=0x7fffffffd658) at emacs.c:1606
```

**Comment by djcb** [comment]
Did you file the issue against emacs?

And as a work-around, you can limit the length of the "subject" field. But this is really an issue with emacs-core, so closing it here.

**Comment by Chris00** [comment]
Bug reported.

**Comment by Chris00** [comment]
The bug is [fixed in Emacs 25](http://debbugs.gnu.org/cgi/bugreport.cgi?bug=24109#115).
